return {
  -- {
  --   "zbirenbaum/copilot.lua",
  --   cmd = "Copilot",
  --   event = "InsertEnter",
  --   config = function()
  --     require("copilot").setup({
  --       suggestion = {
  --         enabled = true,
  --         auto_trigger = true,
  --         debounce = 70,
  --         keymap = {
  --           accept = "<Tab>",   -- bạn có thể đổi thành <Tab> nếu muốn
  --           next = "<M-]>",
  --           prev = "<M-[>",
  --           dismiss = "<C-]>",
  --         },
  --       },
  --       panel = { enabled = false },   -- tắt panel để chỉ hiện inline
  --     })
  --   end,
  -- },
}
