return {
  -- {
  --   -- Debug Framework
  --   "mfussenegger/nvim-dap",
  --   dependencies = {
  --     "rcarriga/nvim-dap-ui",
  --   },
  --   config = function()
  --     require("custom.nvim-dap")
  --   end,
  --   event = "VeryLazy",
  -- },
  -- { "nvim-neotest/nvim-nio" },
  -- {
  --   -- UI for debugging
  --   "rcarriga/nvim-dap-ui",
  --   dependencies = {
  --     "mfussenegger/nvim-dap",
  --   },
  --   config = function()
  --     require("custom.nvim-dap-ui")
  --   end,
  -- },
  -- {
  --   "nvim-neotest/neotest",
  --   requires = {
  --     {
  --       "Issafalcon/neotest-dotnet",
  --     },
  --   },
  --   dependencies = {
  --     "nvim-neotest/nvim-nio",
  --     "nvim-lua/plenary.nvim",
  --     "antoinemadec/FixCursorHold.nvim",
  --     "nvim-treesitter/nvim-treesitter",
  --   },
  -- },
  -- {
  --   "Issafalcon/neotest-dotnet",
  --   lazy = false,
  --   dependencies = {
  --     "nvim-neotest/neotest",
  --   },
  -- },
}
