return {
  -- {
  --   "seblyng/roslyn.nvim",
  --   ---@module 'roslyn.config'
  --   ---@type RoslynNvimConfig
  --   ft = { "cs" },
  --   config = function(_, opts)
  --     require("roslyn").setup(opts)
  --
  --     -- Dotnet
  --     local csharp = require("custom.dotnet")
  --     vim.api.nvim_create_autocmd("FileType", {
  --       pattern = "cs",
  --       callback = function()
  --         local opts = { buffer = true, desc = "C# " }
  --
  --         -- Namespace
  --         vim.keymap.set(
  --           "n",
  --           "<leader>c#n",
  --           csharp.generate_namespace,
  --           vim.tbl_extend("force", opts, { desc = "C# Generate Namespace" })
  --         )
  --
  --         -- Class
  --         vim.keymap.set(
  --           "n",
  --           "<leader>c#c",
  --           csharp.generate_class,
  --           vim.tbl_extend("force", opts, { desc = "C# Generate Class" })
  --         )
  --
  --         -- Interface
  --         vim.keymap.set(
  --           "n",
  --           "<leader>c#i",
  --           csharp.generate_interface,
  --           vim.tbl_extend("force", opts, { desc = "C# Generate Interface" })
  --         )
  --
  --         -- Record (C# 9+)
  --         vim.keymap.set(
  --           "n",
  --           "<leader>c#r",
  --           csharp.generate_record,
  --           vim.tbl_extend("force", opts, { desc = "C# Generate Record" })
  --         )
  --
  --         -- Enum
  --         vim.keymap.set(
  --           "n",
  --           "<leader>c#e",
  --           csharp.generate_enum,
  --           vim.tbl_extend("force", opts, { desc = "C# Generate Enum" })
  --         )
  --
  --         -- === Which Key ===
  --         local wk = require("which-key")
  --         local buffer = vim.api.nvim_get_current_buf()
  --
  --         wk.add({
  --           { "<leader>c#", buffer = buffer, group = "󰌛 C#" },
  --           { "<leader>c#n", buffer = buffer, desc = "Generate Namespace" },
  --           { "<leader>c#c", buffer = buffer, desc = "Generate Class" },
  --           { "<leader>c#i", buffer = buffer, desc = "Generate Interface" },
  --           { "<leader>c#r", buffer = buffer, desc = "Generate Record" },
  --           { "<leader>c#e", buffer = buffer, desc = "Generate Enum" },
  --         })
  --       end,
  --     })
  --   end,
  -- },
}
